### ISSUE TITLE
Inatall svgexport failed on Alpine Linux 3.8+.

### ISSUE THREAD

**Issue by chusiang** [chusiang/gitbook.ansible.role#7]
The error message of 1st.

```
[ chusiang@mac ~/xxx/gitbook.ansible.role/builds/gitbook-3.2 ] (develop) - 18:25
$ docker build -t gitbook:3 .
Sending build context to Docker daemon   2.56kB
Step 1/7 : FROM williamyeh/ansible:alpine3-onbuild
alpine3-onbuild: Pulling from williamyeh/ansible
4fe2ade4980c: Pull complete
e25ba7f769b8: Pull complete
3dd5a81e7c64: Pull complete
Digest: sha256:79c35cbb12c3e7f142a51ce607698697178b58a09b98e961985f5003c74163e9
Status: Downloaded newer image for williamyeh/ansible:alpine3-onbuild
# Executing 4 build triggers
 ---> Running in beaad62a4f26
===> Updating TLS certificates...
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
OK: 68 MiB in 30 packages
Removing intermediate container beaad62a4f26
 ---> Running in 21b322b1c848
Removing intermediate container 21b322b1c848
 ---> Running in b00afaffda0c
===> Diagnosis: host information...
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [],
        "ansible_all_ipv6_addresses": [],
        "ansible_apparmor": {
            "status": "disabled"
        },
        "ansible_architecture": "x86_64",
        "ansible_bios_date": "03/14/2014",
        "ansible_bios_version": "1.00",
        "ansible_cmdline": {
            "BOOT_IMAGE": "/boot/kernel",
            "console": "ttyS0",
            "page_poison": "1",
            "panic": "1",
            "root": "/dev/sr0",
            "text": true,
            "vsyscall": "emulate"
        },
        "ansible_date_time": {
            "date": "2020-03-02",
...

        "ansible_python_version": "2.7.15",
        "ansible_real_group_id": 0,
        "ansible_real_user_id": 0,
        "ansible_selinux": {
            "status": "Missing selinux Python library"
        },
        "ansible_selinux_python_present": false,
        "ansible_service_mgr": "ansible",
        "ansible_swapfree_mb": 2047,
        "ansible_swaptotal_mb": 2047,
        "ansible_system": "Linux",
        "ansible_system_vendor": "NA",
        "ansible_tunl0": {
            "active": false,
            "device": "tunl0",
            "macaddress": "00:00:00:00",
            "mtu": 1480,
            "promisc": false,
            "type": "unknown"
        },
        "ansible_uptime_seconds": 31551,
        "ansible_user_dir": "/root",
        "ansible_user_gecos": "root",
        "ansible_user_gid": 0,
        "ansible_user_id": "root",
        "ansible_user_shell": "/bin/ash",
        "ansible_user_uid": 0,
        "ansible_userspace_architecture": "x86_64",
        "ansible_userspace_bits": "64",
        "ansible_virtualization_role": "guest",
        "ansible_virtualization_type": "docker",
        "gather_subset": [
            "all"
        ],
        "module_setup": true
    },
    "changed": false
}
Removing intermediate container b00afaffda0c
 ---> e53c9e6a112c
Step 2/7 : MAINTAINER Chu-Siang Lai <chusiang@drx.tw>
 ---> Running in 8b3906006aad
Removing intermediate container 8b3906006aad
 ---> 0614c909b844
Step 3/7 : RUN echo "==> Updating package cache ..."     &&       apk update
 ---> Running in 72b2ce999f23
==> Updating package cache ...
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
v3.8.5-9-g168bf00ffd [http://dl-cdn.alpinelinux.org/alpine/v3.8/main]
v3.8.4-286-gda0d4ca4ff [http://dl-cdn.alpinelinux.org/alpine/v3.8/community]
OK: 9579 distinct packages available
Removing intermediate container 72b2ce999f23
 ---> aa1f064c4f4a
Step 4/7 : RUN echo "==> Initializating ..."             &&       apk add --no-cache curl git make        &&       git clone https://github.com/chusiang/gitbook.ansible.role.git &&       cd gitbook.ansible.role                 &&       make init
 ---> Running in ec3cac1eb694
==> Initializating ...
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/7) Installing nghttp2-libs (1.39.2-r0)
(2/7) Installing libssh2 (1.9.0-r1)
(3/7) Installing libcurl (7.61.1-r3)
(4/7) Installing curl (7.61.1-r3)
(5/7) Installing pcre2 (10.31-r0)
(6/7) Installing git (2.18.2-r0)
(7/7) Installing make (4.2.1-r2)
Executing busybox-1.28.4-r1.trigger
OK: 83 MiB in 37 packages
Cloning into 'gitbook.ansible.role'...
#if [ ! -d "ansible-retry" ]; then mkdir "ansible-retry"; fi
ansible-galaxy install -f -p roles -r requirements.yml
- downloading role 'switch-apt-mirror', owned by chusiang
- downloading role from https://github.com/chusiang/switch-apt-mirror.ansible.role/archive/1.0.7.tar.gz
- extracting chusiang.switch-apt-mirror to /tmp/gitbook.ansible.role/roles/chusiang.switch-apt-mirror
- chusiang.switch-apt-mirror (1.0.7) was installed successfully
- downloading role 'vim-and-vi-mode', owned by chusiang
- downloading role from https://github.com/chusiang/vim-and-vi-mode.ansible.role/archive/3.2.0.tar.gz
- extracting chusiang.vim-and-vi-mode to /tmp/gitbook.ansible.role/roles/chusiang.vim-and-vi-mode
- chusiang.vim-and-vi-mode (3.2.0) was installed successfully
Removing intermediate container ec3cac1eb694
 ---> 5f908f4e70aa
Step 5/7 : ENV PLAYBOOK gitbook.ansible.role/setup.yml
 ---> Running in 97623bb83c13
Removing intermediate container 97623bb83c13
 ---> d9fdac9d7e38
Step 6/7 : RUN echo "==> Setuping with Ansible ..."      &&       ansible-playbook-wrapper
 ---> Running in 909acea1fea0
==> Setuping with Ansible ...

PLAY [Setup the GitBook] *******************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [update apt repo cache] ***************************************************
skipping: [localhost]

TASK [install necessary package with apt] **************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `name: {{ item }}`, please use `name: [u'bash-completion', u
'build-essential', u'curl', u'git', u'nodejs', u'nodejs-legacy', u'npm',
u'rsync', u'wget', u'xdg-utils', u'xz-utils']` and remove the loop. This
feature will be removed in version 2.11. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost] => (item=[])

TASK [install calibre with tarball] ********************************************
skipping: [localhost]

TASK [update apk repo cache] ***************************************************
changed: [localhost]

TASK [install necessary package with apk] **************************************
[DEPRECATION WARNING]: Invoking "apk" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `name: {{ item }}`, please use `name: [u'bash', u'build-base',
u'curl', u'gcc', u'git', u'nodejs', u'nodejs-npm', u'rsync']` and remove the
loop. This feature will be removed in version 2.11. Deprecation warnings can be
 disabled by setting deprecation_warnings=False in ansible.cfg.

changed: [localhost] => (item=[u'bash', u'build-base', u'curl', u'gcc', u'git', u'nodejs', u'nodejs-npm', u'rsync'])

TASK [update homebrew repo cache] **********************************************
skipping: [localhost]

TASK [install necessary package with homebrew] *********************************
[DEPRECATION WARNING]: Invoking "homebrew" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `name: {{ item }}`, please use `name: [u'curl', u'git', u'node',
 u'npm']` and remove the loop. This feature will be removed in version 2.11.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
skipping: [localhost] => (item=[])

TASK [install n with npm] ******************************************************
skipping: [localhost]

TASK [switch node to specific edition] *****************************************
skipping: [localhost]

TASK [install necessary package for gitbook with npm] **************************
changed: [localhost] => (item=gitbook-cli)
failed: [localhost] (item=svgexport) => {"changed": false, "cmd": "/usr/bin/npm install --global svgexport", "item": "svgexport", "msg": "ERROR:********@2.1.1 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2020-03-02T10_37_37_597Z-debug.log", "rc": 1, "stderr": "ERROR: Failed to download Chromium r722234! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.\n{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium'\n  -- ASYNC --\n    at BrowserFetcher.<anonymous> (/usr/lib/node_modules/svgexport/node_modules/puppeteer/lib/helper.js:111:15)\n    at Object.<anonymous> (/usr/lib/node_modules/svgexport/node_modules/puppeteer/install.js:66:16)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Function.Module.runMain (module.js:694:10)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'mkdir',\n  path: '/usr/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium' }\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! puppeteer@2.1.1 install: `node install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the puppeteer@2.1.1 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2020-03-02T10_37_37_597Z-debug.log\n", "stderr_lines": ["ERROR: Failed to download Chromium r722234! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.", "{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium'", "  -- ASYNC --", "    at BrowserFetcher.<anonymous> (/usr/lib/node_modules/svgexport/node_modules/puppeteer/lib/helper.js:111:15)", "    at Object.<anonymous> (/usr/lib/node_modules/svgexport/node_modules/puppeteer/install.js:66:16)", "    at Module._compile (module.js:653:30)", "    at Object.Module._extensions..js (module.js:664:10)", "    at Module.load (module.js:566:32)", "    at tryModuleLoad (module.js:506:12)", "    at Function.Module._load (module.js:498:3)", "    at Function.Module.runMain (module.js:694:10)", "    at startup (bootstrap_node.js:204:16)", "    at bootstrap_node.js:625:3", "  errno: -13,", "  code: 'EACCES',", "  syscall: 'mkdir',", "  path: '/usr/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium' }", "npm ERR! code ELIFECYCLE", "npm ERR! errno 1", "npm ERR! puppeteer@2.1.1 install: `node install.js`", "npm ERR! Exit status 1", "npm ERR! ", "npm ERR! Failed at the puppeteer@2.1.1 install script.", "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /root/.npm/_logs/2020-03-02T10_37_37_597Z-debug.log"], "stdout": "/usr/bin/svgexport -> /usr/lib/node_modules/svgexport/bin/index.js\n\n> puppeteer@2.1.1 install /usr/lib/node_modules/svgexport/node_modules/puppeteer\n> node install.js\n\n", "stdout_lines": ["/usr/bin/svgexport -> /usr/lib/node_modules/svgexport/bin/index.js", "", "> puppeteer@2.1.1 install /usr/lib/node_modules/svgexport/node_modules/puppeteer", "> node install.js", ""]}
        to retry, use: --limit @/tmp/gitbook.ansible.role/setup.retry

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1

The command '/bin/sh -c echo "==> Setuping with Ansible ..."      &&       ansible-playbook-wrapper' returned a non-zero code: 2
[ chusiang@mac ~/xxx/gitbook.ansible.role/builds/gitbook-3.2 ] (develop) - 18:37
$
```
```

**Comment by chusiang** [comment]
Fixed on develop branch.

**Comment by chusiang** [comment]
Fixed via Vagrant at Local, but it's not working on Docker container and CI.

**Comment by chusiang** [comment]
It has built success on Alpine Linux v3.10 via Travis CI.

> https://travis-ci.org/chusiang/gitbook.ansible.role/builds/657700193
