### ISSUE TITLE
Install calibre failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by chusiang** [chusiang/gitbook.ansible.role#8]
```
vagrant@ubuntu1804:~$ sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
2020-03-03 09:30:30 URL:https://download.calibre-ebook.com/linux-installer.py [30263/30263] -> "-" [1]
Installing to /opt/calibre
Downloading tarball signature securely...
Using previously downloaded calibre-4.11.2-x86_64.txz
Extracting files to /opt/calibre ...
Extracting application files...
Creating symlinks...
        Symlinking /opt/calibre/lrf2lrs to /usr/bin/lrf2lrs
        Symlinking /opt/calibre/ebook-meta to /usr/bin/ebook-meta
        Symlinking /opt/calibre/calibre-customize to /usr/bin/calibre-customize
        Symlinking /opt/calibre/calibre-smtp to /usr/bin/calibre-smtp
        Symlinking /opt/calibre/calibre-parallel to /usr/bin/calibre-parallel
        Symlinking /opt/calibre/ebook-polish to /usr/bin/ebook-polish
        Symlinking /opt/calibre/web2disk to /usr/bin/web2disk
        Symlinking /opt/calibre/ebook-device to /usr/bin/ebook-device
        Symlinking /opt/calibre/calibre-server to /usr/bin/calibre-server
        Symlinking /opt/calibre/calibredb to /usr/bin/calibredb
        Symlinking /opt/calibre/ebook-viewer to /usr/bin/ebook-viewer
        Symlinking /opt/calibre/calibre-debug to /usr/bin/calibre-debug
        Symlinking /opt/calibre/ebook-edit to /usr/bin/ebook-edit
        Symlinking /opt/calibre/ebook-convert to /usr/bin/ebook-convert
        Symlinking /opt/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
        Symlinking /opt/calibre/lrs2lrf to /usr/bin/lrs2lrf
        Symlinking /opt/calibre/markdown-calibre to /usr/bin/markdown-calibre
        Symlinking /opt/calibre/calibre to /usr/bin/calibre
        Symlinking /opt/calibre/lrfviewer to /usr/bin/lrfviewer
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "site-packages/calibre/linux.py", line 786, in setup_completion
          File "site-packages/calibre/linux.py", line 529, in write_completion
          File "site-packages/calibre/gui2/viewer/main.py", line 12, in <module>
        ImportError: libnss3.so: cannot open shared object file: No such file or directory

Setting up desktop integration...
xdg-desktop-menu: No writable system menu directory found.

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "site-packages/calibre/linux.py", line 897, in setup_desktop_integration
          File "subprocess.py", line 190, in check_call
        CalledProcessError: Command 'xdg-desktop-menu install --noupdate ./calibre-gui.desktop' returned non-zero exit status 3

Creating un-installer: /usr/bin/calibre-uninstall


There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:

Run "calibre" to start calibre
vagrant@ubuntu1804:~$
```

Reference:

* https://calibre-ebook.com/download_linux

**Comment by chusiang** [comment]
Fixed via Vagrant at Local, but it's not working on Docker container and CI.
